import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrateOnClient";
import { getNewAndTrending } from "@/services/service.games";
import NewAndTrending from "./newAndTrending";

export const metadata = {
    title: "New and trending",
    description: "Generated by create next app",
};

export default async function Page() {
    const queryClient = getQueryClient();

    await queryClient.prefetchInfiniteQuery({
        queryKey: ["new-and-trending"],
        queryFn: ({ pageParam = 1 }) => getNewAndTrending(pageParam),
    });

    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <NewAndTrending />
        </Hydrate>
    );
}
