import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrate.client";
import { getNewAndTrending } from "@/services/service.games";
import NewAndTrending from ".";

export const metadata = {
    title: "New and trending",
    description: "Generated by create next app",
};

const Page = async () => {
    const queryClient = getQueryClient();
    await queryClient.prefetchQuery(["new-and-trending"], ({ pageParam = 1 }) =>
        getNewAndTrending(pageParam)
    );
    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <NewAndTrending />
        </Hydrate>
    );
};

export default Page;
