import NewAndTrending from ".";

export const metadata = {
    title: "New and trending",
    description: "Generated by create next app",
};

const Page = () => {
    return <NewAndTrending />;
};

export default Page;
