import Creators from "./creators";

export const metadata = {
    title: "Creators",
    description: "Generated by create next app",
};

const Page = () => {
    return <Creators />;
};

export default Page;
