import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrateOnClient";
import { getBestOfTheYear } from "@/services/service.games";
import BestOfTheYear from ".";

export const metadata = {
    title: "Best of the year",
    description: "Generated by create next app",
};

export default async function Page() {
    const queryClient = getQueryClient();

    await queryClient.prefetchInfiniteQuery({
        queryKey: ["best-of-the-year"],
        queryFn: ({ pageParam = 1 }) => getBestOfTheYear(pageParam),
    });

    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <BestOfTheYear />
        </Hydrate>
    );
}
