import BestOfTheYear from ".";

export const metadata = {
    title: 'Best of the year',
    description: 'Generated by create next app',
};

const Page = () => {
    return (
        <BestOfTheYear />
    );
}

export default Page;