import Details from ".";

export const metadata = {
    title: "Stores Games",
    description: "Generated by create next app",
};

const StoresGames = () => {
    return <Details />;
};

export default StoresGames;
