import StoreDetails from "./storeDetails";

export const metadata = {
    title: "Stores Games",
    description: "Generated by create next app",
};

const StoresGames = () => {
    return <StoreDetails />;
};

export default StoresGames;
