import PopularIn2022 from ".";

export const metadata = {
    title: "Popular in 2022",
    description: "Generated by create next app",
};

const Page = () => {
    return <PopularIn2022 />;
};

export default Page;
