import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrateOnClient";
import { getPopularIn2022 } from "@/services/service.games";
import PopularIn2022 from ".";

export const metadata = {
    title: "Popular in 2022",
    description: "Generated by create next app",
};

export default async function Page() {
    const queryClient = getQueryClient();

    await queryClient.prefetchInfiniteQuery({
        queryKey: ["popular-in-2022"],
        queryFn: ({ pageParam = 1 }) => getPopularIn2022(pageParam),
    });

    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <PopularIn2022 />
        </Hydrate>
    );
}
