import TagDetails from "./tagDetails";

export const metadata = {
    title: "Tags",
    description: "Generated by create next app",
};

const TagsGames = () => {
    return <TagDetails />;
};

export default TagsGames;
