import Details from ".";

export const metadata = {
    title: "Tags",
    description: "Generated by create next app",
};

const TagsGames = () => {
    return <Details />;
};

export default TagsGames;
