import PlatformDetails from "./platformDetails";

export const metadata = {
    title: "PC Games",
    description: "Generated by create next app",
};

const PlatformsGames = () => {
    return <PlatformDetails />;
};

export default PlatformsGames;
