import Details from ".";

export const metadata = {
    title: "PC Games",
    description: "Generated by create next app",
};

const PlatformsGames = () => {
    return <Details />;
};

export default PlatformsGames;
