import Publishers from ".";

export const metadata = {
    title: "Publishers",
    description: "Generated by create next app",
};

const Page = () => {
    return <Publishers />;
};

export default Page;
