import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrateOnClient";
import { getPublishers } from "@/services/service.publishers";
import Publishers from ".";

export const metadata = {
    title: "Publishers",
    description: "Generated by create next app",
};

export default async function Page() {
    const queryClient = getQueryClient();

    await queryClient.prefetchInfiniteQuery({
        queryKey: ["publishers"],
        queryFn: ({ pageParam = 1 }) => getPublishers(pageParam),
    });

    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <Publishers />
        </Hydrate>
    );
}
