import PublisherDetails from "./publisherDetails";

export const metadata = {
    title: "Publishers Games",
    description: "Generated by create next app",
};

const Page = () => {
    return <PublisherDetails />;
};

export default Page;
