import Details from ".";

export const metadata = {
    title: "Publishers Games",
    description: "Generated by create next app",
};

const Page = () => {
    return <Details />;
};

export default Page;
