import DeveloperDetails from "./developerDetails";

export const metadata = {
    title: "Details",
    description: "Generated by create next app",
};

const Page = () => {
    return <DeveloperDetails />;
};

export default Page;
