import './globals.css';
import Navigation from '@/components/Navigation/navigation';
import { ReactQueryProviders } from './providers';

export const metadata = {
  title: 'Rock Star',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
        <body>
          <ReactQueryProviders>
            <Navigation />
            {children}
          </ReactQueryProviders>
        </body>
    </html>
  )
}
