import './globals.css';

import { ReactQueryProviders } from './providers';
import WebNavigation from '@/components/Navigation/index.js';
import Header from '@/components/Header';

export const metadata = {
  title: 'Rock Star',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
        <body>
          <ReactQueryProviders>
            <main>
              {/* <Navigation /> */}
              <Header />
              <section className="lg:flex">
                <aside className="hidden lg:block lg:fixed lg:left-0 lg:top-0 lg:h-screen lg:p-4 lg:w-60">
                  <WebNavigation />
                </aside>
                <div className="lg:flex-1 lg:ml-60">
                  {children}
                </div>
              </section>
            </main>
          </ReactQueryProviders>
        </body>
    </html>
  )
}
