import Stores from "./stores";

export const metadata = {
    title: "Stores",
    description: "Generated by create next app",
};

const Page = () => {
    return <Stores />;
};

export default Page;
