import Platforms from ".";

export const metadata = {
    title: "Platorms",
    description: "Generated by create next app",
};

const Page = () => {
    return <Platforms />;
};

export default Page;
