import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrateOnClient";
import { getPlatforms } from "@/services/service.platform";
import Platforms from ".";

export const metadata = {
    title: "Platorms",
    description: "Generated by create next app",
};

export default async function Page() {
    const queryClient = getQueryClient();

    await queryClient.prefetchInfiniteQuery({
        queryKey: ["platforms"],
        queryFn: () => getPlatforms(),
    });

    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <Platforms />
        </Hydrate>
    );
}
