import Developers from "./developers";

export const metadata = {
    title: "Developers",
    description: "Generated by create next app",
};

const Page = () => {
    return <Developers />;
};

export default Page;
