import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrateOnClient";
import { getGenres } from "@/services/service.genres";
import Genres from ".";

export const metadata = {
    title: "Genres",
    description: "Generated by create next app",
};

export default async function Page() {
    const queryClient = getQueryClient();

    await queryClient.prefetchInfiniteQuery({
        queryKey: ["genres"],
        queryFn: () => getGenres(),
    });

    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <Genres />
        </Hydrate>
    );
}
