import Genres from "./genres";

export const metadata = {
    title: "Genres",
    description: "Generated by create next app",
};

const Page = () => {
    return <Genres />;
};

export default Page;
