import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrateOnClient";
import { getTags } from "@/services/service.tags";
import Tags from ".";

export const metadata = {
    title: "Tags",
    description: "Generated by create next app",
};

export default async function Page() {
    const queryClient = getQueryClient();

    await queryClient.prefetchInfiniteQuery({
        queryKey: ["tags"],
        queryFn: ({ pageParam = 1 }) => getTags(pageParam),
    });

    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <Tags />
        </Hydrate>
    );
}
