import Detail from ".";

export const metadata = {
    title: "Action Games",
    description: "Generated by create next app",
};

const GenreGames = () => {
    return <Detail />;
};

export default GenreGames;
