import GenreDetails from "./genreDetails";

export const metadata = {
    title: "Action Games",
    description: "Generated by create next app",
};

const GenreGames = () => {
    return <GenreDetails />;
};

export default GenreGames;
