import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrateOnClient";
import { getAllGames } from "@/services/service.games";
import Games from ".";

export const metadata = {
    title: "All Games",
    description: "Generated by create next app",
};

export default async function Page() {
    const queryClient = getQueryClient();

    await queryClient.prefetchInfiniteQuery({
        queryKey: ["games"],
        queryFn: ({ pageParam = 1 }) => getAllGames(pageParam),
    });

    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <Games />
        </Hydrate>
    );
}
