import { dehydrate } from "@tanstack/react-query";

import getQueryClient from "@/utils/getQueryCilent";
import Hydrate from "@/utils/hydrateOnClient";
import { getAllTimeTop250 } from "@/services/service.games";
import AllTimeTop250 from "./index";

export const metadata = {
    title: "All time top 250",
    description: "Generated by create next app",
};

export default async function Page() {
    const queryClient = getQueryClient();

    await queryClient.prefetchInfiniteQuery({
        queryKey: ["all-time-top-200"],
        queryFn: ({ pageParam = 1 }) => getAllTimeTop250(pageParam),
    });

    const dehydrateState = dehydrate(queryClient);

    return (
        <Hydrate state={dehydrateState}>
            <AllTimeTop250 />
        </Hydrate>
    );
}
