import Home from "./home";

export const metadata = {
    title: 'All time top 250',
    description: 'Generated by create next app',
}

const Page = () => {
    return (
        <Home />
    );
};

export default Page;
