import AllTimeTop250 from "./index";

export const metadata = {
    title: 'All time top 250',
    description: 'Generated by create next app',
}

const Page = () => {
    return (
        <AllTimeTop250 />
    );
};

export default Page;
