import Details from ".";

export const metadata = {
    title: 'Creator Details',
    description: 'Generated by create next app',
};

const Page = () => {
    return (
        <Details />
    );
}

export default Page;