import CreatorDetails from "./creatorDetails";

export const metadata = {
    title: "Creator Details",
    description: "Generated by create next app",
};

const Page = () => {
    return <CreatorDetails />;
};

export default Page;
